app:
  package-name: com.example
  module-name: demo
#  xml子包名称
  mapper-xml-package:
  table-name: t_user
#  设置数据层接口名，%s为占位符 %sDao
  mapper-name:
#  实体类包名
  entity-package-name: pojo.entity
#  数据层包名
  mapper-package-name:
  controller-package-name:
  table-prefix: t_
  logic-delete-field-name: isDelete
  version-field-name: version
  author: zjm
#  设置完之后是否打开资源管理器
  open: false
#  设置是否覆盖原始生成的文件
  file-override: true
  swagger: false
#  服务代码路径
  service-path: /src/main/java
#  mapper文件路径
  mapper-path: /src/main/resources/mapper/
#  mapper文件后缀
  mapper-suffix: Mapper
#  如果模板引擎是 freemarker
  template-path: /templates/mapper.xml.ftl
#  如果模板引擎是 velocity
#  template-path: /templates/mapper.xml.vm
#  公共字段，这里写的字段不会生成到 entity 中
  super-entity-columns:
  entity-lombok-model: true
#  你自己的父类实体,没有就不用设置!
  super-entity-class:
#  你自己的父类控制器,没有就不用设置!
  super-controller-class:
#  生成基本ResultMap
  base-result-map: true
#  生成基本ColumnList
  base-column-list: true
  Swagger2: true
#  是否生成实体时，生成字段注解
  entity-table-field-annotation-enable: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driver-class-name: org.postgresql.Driver