app:
  package-name: com.ttran
  #  package-name: com.bwvision.busbox.business
  module-name: demo
#  module-name: nbbus
  #  module-name: busbox
  #  xml子包名称
  #  mapper-xml-package: business/busbox/
  mapper-xml-package:
  table-name: sys_role
  # mysql数据库 不用写；oracle 一般为 NAVTECH 注意大小写；pgsql 一般为 public；见具体情况
  schema-name:
#  schema-name: NAVTECH
#  schema-name: public
#  多数据源时不同数据库名称
  dynamic-datasource: master
  #  是否使用通用的查询DTO
#  is-use-common-query-dto: true
  is-use-common-query-dto: false
  #  是否为关系表
#  is-relation: true
  is-relation: false
#  是否只做查询
  is-only-query: false
#  is-only-query: true
  #  是否使用LocalDate
#  is-use-LocalDate: false
  is-use-LocalDate: true
  #  设置数据层接口名，%s为占位符 %sDao
  mapper-name: '%sMapper'
  #  设置实体类名
  entity-name: '%sPo'
  dto-save-name: '%sSaveDTO'
  dto-query-name: '%sQueryDTO'
  vo-name: '%sVo'
  mapstruct-name: '%sTransform'
  #  设置控制类名
  controller-name: '%sController'
  ##  entity-name: '%sEntity'
  #  设置服务接口名
  service-name: 'I%sService'
  #  设置服务实现类名
  service-impl-name: '%sServiceImpl'
  #  实体类包名
  entity-package-name: pojo.po
  #  entity-package-name: domain.entity
  #  服务接口包名
  service-package-name: service
  #  服务接口实现类包名
  service-impl-package-name: service.impl
  #  数据层包名
  #  mapper-package-name:
  mapper-package-name: mapper
  #  控制层包名
  controller-package-name: controller
  #  自定义文件包名
  other-package-name: pojo
  dto-package-name: dto
  vo-package-name: vo
  mapstruct-package-name: mapstruct
  table-prefix: t_,c_,p_,SYS_,d_,sys_
#  是否已全局配置逻辑删除字段
#  is-global-config-logic-delete: true
  is-global-config-logic-delete: false
  #  逻辑删除字段是否设置了默认值
#  is-logic-delete-field-default: true
  is-logic-delete-field-default: false
  logic-delete-field-name: is_delete
#  logic-delete-field-name: repeated
#  logic-delete-field-name: deleted
  create-time-field-name: create_time
  create-user-field-name: create_user
  update-time-field-name: update_time
  update-user-field-name: update_user
  version-field-name: version
  author: zjm
  #  设置完之后是否打开资源管理器
  open: false
  #  设置是否覆盖原始生成的文件
  file-override: true
  ##  服务代码路径
  service-path: /src/main/java
  #  mapper文件路径
  mapper-path: /src/main/resources/mapper/
  #  mapper文件后缀
  mapper-suffix: Mapper
  #  如果模板引擎是 freemarker
  template-path: /template/mapper.xml.ftl
  #  如果模板引擎是 velocity
  #  template-path: /templates/mapper.xml.vm
  #  公共字段，这里写的字段不会生成到 entity 中
  super-entity-columns:
  entity-lombok-model: true
  #  你自己的父类实体,没有就不用设置!
  super-entity-class:
  #  super-entity-class: com.bwvision.deverloper.dependencies.database.domain.BaseEntity
  #  你自己的父类控制器,没有就不用设置!
  super-controller-class:
  #  生成基本ResultMap
  base-result-map: true
  #  生成基本ColumnList
  base-column-list: true
  Swagger2: true
  #  Swagger2: false
  #  是否生成实体时，生成字段注解
  entity-table-field-annotation-enable: true
  #  是否开启mapper注解
  mapper-annotation-enable: true

spring:
  datasource:
#    url: jdbc:mysql://10.16.5.141:3306/driver_salary?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://10.16.5.141:3306/car_park?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://10.16.5.141:3306/car_dispatch?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://10.16.5.141:3306/multimedia?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://10.16.5.141:3306/zhtj?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://10.16.5.141:3306/labor_cost?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    url: jdbc:mysql://10.16.5.141:3306/safety_analysis?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://10.16.3.57:3306/nb_sso_pro?characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: ttran.cn
    driver-class-name: com.mysql.cj.jdbc.Driver
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://10.16.5.140;DatabaseName=inspectsystem
#    username: INSPECT_PROJ
#    password: INSPECT
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://26.16.0.186;DatabaseName=Salary
#    username: kxc_pr
#    password: kxc@nbgj
#    driver-class-name: org.postgresql.Driver
#    password: ttran.cn
#    password: Nbgj@967277
#    url: jdbc:postgresql://10.16.5.141:5432/busbox-business?characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai
#    url: jdbc:postgresql://47.97.206.48:5432/busbox-business?characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: postgres
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@10.16.5.104:1521:orcl
#    username: navtech
#    password: gps@Nbtc
#    url: jdbc:postgresql://10.16.3.80:2345/gpdb?characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: gpadmin
#    password: WhHik@3456+
#    driver-class-name: org.postgresql.Driver