app:
  package-name: com.ttran
  #  package-name: com.bwvision.busbox.business
  module-name: nbbus
#  module-name: demo
  #  module-name: busbox
  #  xml子包名称
  #  mapper-xml-package: business/busbox/
  mapper-xml-package: master
#  mapper-xml-package: hr
  table-name: GJ_SITE_TOP
  #  是否为关系表
  is-relation: true
#  is-relation: false
#  is-use-LocalDate: false
  is-use-LocalDate: true
  #  设置数据层接口名，%s为占位符 %sDao
  mapper-name:
  #  设置实体类名
  entity-name: '%sPo'
  #  entity-name: '%sEntity'
  #  设置接口名
  service-name: 'I%sService'
  #  实体类包名
  entity-package-name: pojo.po
  #  entity-package-name: domain.entity
  #  数据层包名
  #  mapper-package-name:
  mapper-package-name: mapper
  controller-package-name:
  table-prefix: t_,c_,p_,SYS_
  logic-delete-field-name: is_delete
  version-field-name: version
  author: zjm
  #  设置完之后是否打开资源管理器
  open: false
  #  设置是否覆盖原始生成的文件
  file-override: true
  swagger: false
  #  服务代码路径
  service-path: /src/main/java
  #  mapper文件路径
  mapper-path: /src/main/resources/mapper/
  #  mapper文件后缀
  mapper-suffix: Mapper
  #  如果模板引擎是 freemarker
  template-path: /templates/mapper.xml.ftl
  #  如果模板引擎是 velocity
  #  template-path: /templates/mapper.xml.vm
  #  公共字段，这里写的字段不会生成到 entity 中
  super-entity-columns:
  entity-lombok-model: true
  #  你自己的父类实体,没有就不用设置!
  super-entity-class: com.baomidou.mybatisplus.extension.activerecord.Model
  #  super-entity-class: com.bwvision.deverloper.dependencies.database.domain.BaseEntity
  #  你自己的父类控制器,没有就不用设置!
  super-controller-class:
  #  生成基本ResultMap
  base-result-map: true
  #  生成基本ColumnList
  base-column-list: true
  Swagger2: true
  #  Swagger2: false
  #  是否生成实体时，生成字段注解
  entity-table-field-annotation-enable: true
  create-time-field-name: create_time
#  create-time-field-name: CREATE_DATE
  create-user-field-name: create_user
#  update-time-field-name: update_time
  update-time-field-name: UPDATE_DATE
  update-user-field-name: update_user

spring:
  datasource:
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:sqlserver://10.16.5.140;DatabaseName=inspectsystem
#    url: jdbc:postgresql://47.97.206.48:5432/thirdparty?characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: postgres
#    username: INSPECT_PROJ
#    password: ttran.cn
#    password: INSPECT
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://26.16.0.186;DatabaseName=Salary
#    username: kxc_pr
#    password: kxc@nbgj
#    driver-class-name: org.postgresql.Driver
#    password: ttran.cn
#    url: jdbc:postgresql://10.16.5.141:5432/busbox-business?characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: postgres
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@10.16.5.104:1521:orcl
    username: navtech
    password: gps@Nbtc
#    url: jdbc:postgresql://10.16.3.80:2345/gpdb?characterEncoding=utf8&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=Asia/Shanghai
#    username: gpadmin
#    password: WhHik@3456+
#    driver-class-name: org.postgresql.Driver